[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"

[compat]
CSV = "0.10"
DataFrames = "1.6"
GenieFramework = "1.19"
PlotlyBase = "0.8"
